#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');

const defaultConfigPath = path.resolve(__dirname, './.config');
const projectConfigPath = path.resolve(__dirname, './config.json');

if(fs.existsSync(projectConfigPath)){
    const defaultConfig = JSON.parse(fs.readFileSync(defaultConfigPath));
    const projectConfig = JSON.parse(fs.readFileSync(projectConfigPath));

    fs.writeFileSync(
        projectConfigPath,
        JSON.stringify(Object.assign(defaultConfig, projectConfig), null, 4)
    )
}else{
    fs.createReadStream(defaultConfigPath).pipe(fs.createWriteStream(projectConfigPath));
}
