#!/bin/bash

reset="\e[0m"
red="\e[0;31m"
green="\e[0;32m"
yellow="\e[0;33m"
cyan="\e[0;36m"
white="\e[0;37m"

cd "$(dirname $0)"

cp -rf ./.manifest/* ./.manifest.bak
cp -rf ./.manifest.next/* ./.manifest

pm2 reload zktravel-manage